name: Build Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:     
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Set up MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
          base-devel 
          gcc
          cmake
          mingw-w64-ucrt-x86_64-go
    
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      uses: threeal/cmake-action@v1.2.0
      with:
        run-build: true
        c-compiler: gcc
        cxx-compiler: g++

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   # Execute tests defined by the CMake configuration.
    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #   run: ctest -C ${{env.BUILD_TYPE}}

